---
- hosts: "{{ item }}"
  become: yes
  become_method: sudo
  tasks:
    - name: Install packages on Centos
      when: ansible_distribution == "CentOS"
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ items }}"
    - name: Install packages on Ubuntu and Debian
      when: ansible_os_family == "Debian"
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ item }}"
